import type { Road } from "./types";

// Approximate polylines for well-known driving roads. Coordinates are
// hand-simplified so the map has something to render without a database.
// Format: [lng, lat].
export const seedRoads: Road[] = [
  {
    id: "seed-tail-of-the-dragon",
    slug: "tail-of-the-dragon",
    name: "Tail of the Dragon (US-129)",
    region: "Tennessee / North Carolina",
    summary:
      "318 curves in 11 miles through the Great Smoky Mountains — the most famous driving road in the eastern US.",
    description:
      "A tight, technical ridge-top two-lane between Deals Gap, NC and the Calderwood Dam in TN. Constant left-right transitions, blind crests, and no cross streets or driveways for the full 11 miles. Expect motorcycles, photographers at 'Killboy' curves, and enforcement. Arrive early on weekdays for a clean run.",
    distance_miles: 11,
    elevation_gain_ft: 600,
    est_drive_minutes: 25,
    difficulty: "spirited",
    surface_quality: "good",
    traffic_notes: "Very crowded spring–fall weekends. Heavy motorcycle traffic.",
    characteristics: ["tight switchbacks", "ridge-top", "no intersections"],
    hazards: ["blind crests", "gravel in apexes", "deer at dawn/dusk"],
    best_time: "Weekday mornings, late April to early June",
    start_lat: 35.468,
    start_lng: -83.922,
    end_lat: 35.54,
    end_lng: -83.98,
    path: [
      [-83.922, 35.468],
      [-83.934, 35.472],
      [-83.942, 35.482],
      [-83.948, 35.494],
      [-83.955, 35.505],
      [-83.962, 35.514],
      [-83.97, 35.522],
      [-83.975, 35.532],
      [-83.98, 35.54],
    ],
  },
  {
    id: "seed-blue-ridge-parkway-grandfather",
    slug: "blue-ridge-parkway-grandfather",
    name: "Blue Ridge Parkway — Grandfather Mountain",
    region: "North Carolina",
    summary:
      "Sweeping ridge-line cruise with the Linn Cove Viaduct and some of the best fall color on the east coast.",
    description:
      "A relaxed, scenic stretch of the Blue Ridge Parkway with long sweepers, milepost overlooks, and the engineering showpiece of the Linn Cove Viaduct curving around Grandfather Mountain. Speed limit is 45 and strictly enforced; this is a cruise, not an attack.",
    distance_miles: 24,
    elevation_gain_ft: 1800,
    est_drive_minutes: 50,
    difficulty: "easy",
    surface_quality: "excellent",
    traffic_notes: "Packed at peak leaf season (mid-October). No commercial vehicles.",
    characteristics: ["long sweepers", "overlooks", "fall color"],
    hazards: ["fog above 4,000 ft", "wildlife", "seasonal closures for ice"],
    best_time: "Mid-October weekdays, or late May",
    start_lat: 36.102,
    start_lng: -81.8,
    end_lat: 35.94,
    end_lng: -81.93,
    path: [
      [-81.8, 36.102],
      [-81.82, 36.08],
      [-81.84, 36.05],
      [-81.86, 36.02],
      [-81.88, 35.995],
      [-81.9, 35.97],
      [-81.92, 35.955],
      [-81.93, 35.94],
    ],
  },
  {
    id: "seed-angeles-crest",
    slug: "angeles-crest-highway",
    name: "Angeles Crest Highway (CA-2)",
    region: "California",
    summary:
      "66 miles from La Cañada to Wrightwood — LA's backyard mountain road, from chaparral to 7,900 ft pines.",
    description:
      "One of the great mountain highways in North America, climbing out of the LA basin into the San Gabriels. Good pavement, proper camber, mix of tight second-gear corners and long third/fourth-gear sweepers. Snow closures above Clear Creek are common November–April.",
    distance_miles: 66,
    elevation_gain_ft: 6800,
    est_drive_minutes: 140,
    difficulty: "spirited",
    surface_quality: "good",
    traffic_notes: "Weekend bicyclists below Red Box; CHP presence.",
    characteristics: ["long climb", "mixed corners", "altitude"],
    hazards: ["rockfall", "snow/ice above 5,000 ft", "no cell service for long stretches"],
    best_time: "Weekday mornings May–October",
    start_lat: 34.21,
    start_lng: -118.12,
    end_lat: 34.36,
    end_lng: -117.63,
    path: [
      [-118.12, 34.21],
      [-118.08, 34.22],
      [-118.02, 34.24],
      [-117.96, 34.26],
      [-117.9, 34.28],
      [-117.84, 34.3],
      [-117.78, 34.32],
      [-117.72, 34.34],
      [-117.67, 34.35],
      [-117.63, 34.36],
    ],
  },
  {
    id: "seed-going-to-the-sun",
    slug: "going-to-the-sun-road",
    name: "Going-to-the-Sun Road",
    region: "Montana — Glacier National Park",
    summary:
      "50 miles across the continental divide, with Logan Pass at 6,646 ft and walls of ice and rock on both sides.",
    description:
      "Arguably the most scenic public road in the United States. The climb up to Logan Pass from either side involves narrow shelves carved into the mountain with no guardrails, waterfalls crossing the pavement, and drops that would humble anyone. Vehicle length restriction (21 ft) applies.",
    distance_miles: 50,
    elevation_gain_ft: 3400,
    est_drive_minutes: 130,
    difficulty: "moderate",
    surface_quality: "good",
    traffic_notes: "Timed-entry reservation required in season. Fully closed late fall to early summer.",
    characteristics: ["alpine", "cliff shelves", "national park"],
    hazards: ["narrow lanes", "cyclists", "bighorn sheep in road"],
    best_time: "Late June to mid-September",
    start_lat: 48.497,
    start_lng: -113.987,
    end_lat: 48.697,
    end_lng: -113.43,
    path: [
      [-113.987, 48.497],
      [-113.93, 48.52],
      [-113.87, 48.55],
      [-113.8, 48.59],
      [-113.72, 48.62],
      [-113.66, 48.65],
      [-113.58, 48.68],
      [-113.5, 48.695],
      [-113.43, 48.697],
    ],
  },
  {
    id: "seed-highway-1-big-sur",
    slug: "highway-1-big-sur",
    name: "Highway 1 — Big Sur",
    region: "California",
    summary:
      "90 miles of Pacific cliff-edge driving between Carmel and San Simeon, past Bixby Creek Bridge and McWay Falls.",
    description:
      "The quintessential American coastal drive. Long ocean sweepers punctuated by iconic bridges and pull-offs. Slow-moving RVs and photographers slow progress; patience is the skill here, not speed. Check Caltrans for landslide closures before committing.",
    distance_miles: 90,
    elevation_gain_ft: 4200,
    est_drive_minutes: 180,
    difficulty: "easy",
    surface_quality: "mixed",
    traffic_notes: "Slow summer traffic; use turnouts. Periodic landslide closures.",
    characteristics: ["coastal", "iconic bridges", "photography"],
    hazards: ["landslides", "fog", "wildlife on road at night"],
    best_time: "Weekday mornings in September/October",
    start_lat: 36.55,
    start_lng: -121.92,
    end_lat: 35.65,
    end_lng: -121.19,
    path: [
      [-121.92, 36.55],
      [-121.9, 36.45],
      [-121.85, 36.35],
      [-121.8, 36.25],
      [-121.73, 36.15],
      [-121.65, 36.05],
      [-121.55, 35.95],
      [-121.45, 35.85],
      [-121.35, 35.75],
      [-121.25, 35.7],
      [-121.19, 35.65],
    ],
  },
  {
    id: "seed-beartooth",
    slug: "beartooth-highway",
    name: "Beartooth Highway (US-212)",
    region: "Montana / Wyoming",
    summary:
      "Switchbacks up to 10,947 ft — Charles Kuralt called it 'the most beautiful roadway in America.'",
    description:
      "From Red Lodge, MT up and over the Beartooth Pass and down to the northeast entrance of Yellowstone. Tight switchbacks to tree-line, then a high alpine plateau at nearly 11,000 ft. Closed by snow from mid-October to late May most years.",
    distance_miles: 68,
    elevation_gain_ft: 5500,
    est_drive_minutes: 160,
    difficulty: "moderate",
    surface_quality: "good",
    traffic_notes: "RVs common in summer; patient passing required.",
    characteristics: ["high-altitude", "switchbacks", "alpine plateau"],
    hazards: ["snow squalls in summer", "altitude effects", "wildlife"],
    best_time: "Late June through September",
    start_lat: 45.186,
    start_lng: -109.249,
    end_lat: 44.93,
    end_lng: -109.85,
    path: [
      [-109.249, 45.186],
      [-109.3, 45.14],
      [-109.38, 45.08],
      [-109.46, 45.04],
      [-109.55, 45.0],
      [-109.65, 44.97],
      [-109.75, 44.95],
      [-109.85, 44.93],
    ],
  },
];
